services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://user:password@db:5432/mydb
      - SECRET_KEY=supersecretkey
      - JWT_SECRET_KEY=superjwtsecret
    depends_on:
      - db

volumes:
  db_data:
